name: todo_spring_2025
description: "TODO Spring 2025"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  sign_in_button: ^3.2.0
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.5
  google_fonts: ^6.2.1
  flutter_local_notifications: ^19.0.0
  app_settings: ^6.1.1
  timezone: ^0.10.0
  speech_to_text: ^7.0.0
  sliding_up_panel: ^2.0.0+1
  intl: ^0.20.2
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  cached_network_image: ^3.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo.png