// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4ppw3E6iDpwRbpNg0YyF8msubmNg6BXc',
    appId: '1:972715380151:web:30cf2a0b168737612d6c32',
    messagingSenderId: '972715380151',
    projectId: 'devtask-15a9f',
    authDomain: 'devtask-15a9f.firebaseapp.com',
    storageBucket: 'devtask-15a9f.firebasestorage.app',
    measurementId: 'G-C69T16JGM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcI9vNW8KdsOsJP5CbaN8e_OY2rQ0igAY',
    appId: '1:972715380151:android:695334b4195cb1642d6c32',
    messagingSenderId: '972715380151',
    projectId: 'devtask-15a9f',
    storageBucket: 'devtask-15a9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5qrEjssNz34YbrONWQsfH5Li8_drq3BE',
    appId: '1:972715380151:ios:313cd435231431a12d6c32',
    messagingSenderId: '972715380151',
    projectId: 'devtask-15a9f',
    storageBucket: 'devtask-15a9f.firebasestorage.app',
    iosBundleId: 'com.example.todoSpring2025',
  );

}